# Generated by Django 3.2.8 on 2021-12-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211217_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default=12345, max_length=11),
            preserve_default=False,
        ),
    ]
