# Generated by Django 3.2.8 on 2021-12-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0003_remove_gardener_zip_code'),
        ('plant_masters', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
        migrations.AddField(
            model_name='plant',
            name='gardener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gardeners.gardener'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='master_plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plant_masters.plants_master'),
            preserve_default=False,
        ),
    ]
