# Generated by Django 3.2.8 on 2021-12-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardener',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gardener',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gardener',
            name='street',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gardener',
            name='zip_code',
            field=models.IntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
