# Generated by Django 3.2.8 on 2021-12-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0002_auto_20211221_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardener',
            name='zip_code',
        ),
    ]
