# Generated by Django 3.2.8 on 2021-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0004_auto_20211223_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardener',
            name='zipcode',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
