# Generated by Django 3.2.8 on 2022-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0005_gardener_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardener',
            name='email',
        ),
        migrations.AlterField(
            model_name='gardener',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
