# Generated by Django 3.2.8 on 2022-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants_master',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
